from fastapi import FastAPI, Response

app = FastAPI(title="Podcastinator")

@app.get("/{feed_name}.rss")
async def get_rss_feed(feed_name: str):
    # Dynamic feed generation logic
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{feed_name.replace('-', ' ')}</title>
    <link>https://podcasts.jeff.selfip.com/{feed_name}.rss</link>
    <description>Generated by Podcastinator</description>
  </channel>
</rss>"""
    return Response(content=content, media_type="application/rss+xml")
