import tomllib
from pathlib import Path
from fastapi import FastAPI, Response

app = FastAPI(title="Podcastinator")

@app.get("/{feed_name}.rss")
async def get_rss_feed(feed_name: str):
    # Dynamicly generate and send the RSS feed for the requested podcast.
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{feed_name.replace('_', ' ')}</title>
    <link>https://podcasts.jeff.selfip.com/{feed_name}.rss</link>
    <description>Generated by Podcastinator</description>
  </channel>
</rss>
"""
    return Response(content=content, media_type="application/rss+xml")

def load_config(feed_name: str) -> dict:
    # Get our configuration directory.
    conf_dir = Path.home() / ".config" / "podcastinator"

    # Compose the configuration filename based on the feed name.
    fn = conf_dir / f"{Path(feed_name).stem}.toml"

    # Make sure our configuration directory exists.
    conf_dir.mkdir(parents=True, exist_ok=True)

    # 
    if not fn.exists():
        with open(fn, "w+") as f:
            f.write("""\
--- Feed Descriptors ---
<title>: The official name of the podcast.
<link>: The main website for the show.
<description>: A short summary of what the podcast is about.
<language>: The primary language spoken in the podcast (e.g., en-us).
<copyright>: Notice of legal ownership or rights.
<managingEditor>: Email address of the person responsible for editorial content.
<webMaster>: Email address of the person responsible for technical upkeep.
<pubDate>: The date and time when the feed was last updated.
<lastBuildDate>: When the data in the feed was last changed.
<generator>: The software or tool used to build the feed.
<image>: A small traditional RSS logo (contains <url>, <title>, <link>).
<category>: General category classification.
<itunes:author>: The name of the artist or company that made the show.
<itunes:summary>: A longer summary for podcast apps.
<itunes:owner>: Contact info for the show owner (contains <itunes:name> and <itunes:email>).
<itunes:image>: The main high-resolution cover art (at least 1400x1400 pixels).
<itunes:category>: Specific primary and secondary podcast categories and subcategories.
<itunes:explicit>: Tells if the show has adult content (true or false).
<itunes:type>: Tells if episodes run in order (serial) or standalone (episodic).

--- Episode Descriptors ---
<title>: The name of the specific episode.
<description>: The show notes or summary for this episode.
<enclosure>: The actual media file link, file size in bytes, and file type (e.g., audio/mpeg).
<guid>: A unique permanent ID for the episode (often set to isPermaLink="false").
<pubDate>: The release date and time for the episode.
<link>: A webpage link specific to this episode.
<itunes:title>: The title used specifically in podcast apps.
<itunes:duration>: The length of the episode in seconds or HH:MM:SS format.
<itunes:episode>: The sequence number of the episode.
<itunes:season>: The season number of the show.
<itunes:episodeType>: The type of release (full, trailer, or bonus).
<itunes:explicit>: Tells if this specific episode has adult content (true or false).
<itunes:image>: Custom cover art for just this episode.
<itunes:summary>: A short text summary for the episode.
""")
        raise FileNotFoundError(f"Config file not found at {CONFIG_PATH}")
        
    with open(fn, "rb") as f:
        return tomllib.load(f)
        
